#!/usr/bin/env bash
# Sets up a custom 404 page for nginx

# Create custom 404 page
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html

# Edit nginx configuration
sed -i '/error_page 404 /c\error_page 404 /custom_404.html;' /etc/nginx/sites-available/default

# Restart nginx without using systemctl
service nginx restart
