#!/usr/bin/env bash
# Fix Nginx to listen on port 80

# Check if the Nginx default config file exists and update it
[ -f /etc/nginx/sites-available/default ] && sed -i "s/listen 8080;/listen 80;/" /etc/nginx/sites-available/default

# Restart Nginx using service
service nginx restart
