#!/usr/bin/env bash
# This script configures Ubuntu server with specified IP settings

cp /etc/hosts ~/hosts.backup

grep -qxF '127.0.0.2	localhost' /etc/hosts || echo '127.0.0.2	localhost' | tee -a /etc/hosts
grep -qxF '8.8.8.8	facebook.com' /etc/hosts || echo '8.8.8.8	facebook.com' | tee -a /etc/hosts
