#!/usr/bin/env bash
# Configures Nginx to add a custom HTTP response header

# Install Nginx if it's not already installed
sudo apt-get update
sudo apt-get install -y nginx

# Get the hostname of the server
HOSTNAME=$(hostname)

# Configure Nginx to add the custom header
sudo sed -i "/server_name _;/a \\\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default

# Restart Nginx to apply the changes
sudo systemctl restart nginx
