#!/usr/bin/env bash
# This script runs the 'whoami' command under the user passed as an argument

if [ $# -eq 1 ]; then
    if id "$1" &>/dev/null; then
        su - "$1" -c 'whoami'
    else
        echo "Error: User '$1' does not exist."
    fi
else
    echo "Usage: $0 <username>"
fi
