#!/usr/bin/env bash
# Configures Nginx to run as nginx user and listen on port 8080

sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/ listen [^;]*/ listen 8080/" /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
pkill -o nginx && service nginx restart

