#!/usr/bin/env bash
# Configures Nginx to run as nginx user and listen on port 8080

sed -i 's/user [^;]*/user nginx/' /etc/nginx/nginx.conf

sed -i '/^http {/a \\tserver { listen 8080 default_server; }' /etc/nginx/nginx.conf

service nginx restart
